name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Project Checked Successfully
        run: echo "HTML/CSS/JS project - No dependencies to install."
